# ESPECIFIES WHICH FILES, COMPILER, AND FLAGS WILL USE
OBJS = PixelEngine.cpp main.cpp
C = g++
Flags = -w -lSDL2

# OBJS_NAME defines the name of our executable

OBJ_NAME = Run

# define the target of our executable
all : $(OBJS)
	$(C) $(OBJS) $(Flags) -o $(OBJ_NAME) -g
